version: '3.5'

services:
  postgres:
    container_name: postgres-colmena
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5434:5432'
    networks:
      - colmena-network
    restart: unless-stopped
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    image: nodejs
    container_name: nodejs-colmena
    restart: unless-stopped
    env_file: .env.docker
    ports:
      - '8001:8080'
    networks:
      - colmena-network
networks:
  colmena-network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
